import {mkdir,copyFile,writeFile,readFile,rm} from 'node:fs/promises';
import {resolve,join,dirname} from 'node:path';
const out=resolve('.local/site-dist');
if(dirname(out)!==resolve('.local'))throw Error('Unexpected output directory');
await rm(out,{recursive:true,force:true});await mkdir(join(out,'assets'),{recursive:true});
for(const name of ['index.html','style.css'])await copyFile('site/'+name,join(out,name));
for(const name of ['shep-logo.png','chat.png','sessions.png','controls.png','attention.png','video-poster.jpg','quotadeck.png','theme-ghostty.png','theme-matrix.png','theme-xp.png'])await copyFile('docs/images/'+name,join(out,'assets',name));
await copyFile('docs/video/shep-demo.mp4',join(out,'assets/shep-demo.mp4'));
await copyFile('site/demo.vtt',join(out,'assets/demo.vtt'));
await copyFile('site/herdr-logo.svg',join(out,'assets/herdr-logo.svg'));
await writeFile(join(out,'.nojekyll'),'');
await writeFile(join(out,'notices.txt'),await readFile('THIRD-PARTY-NOTICES.md','utf8')+'\n\n'+await readFile('licenses/Heeler-Apache-2.0.txt','utf8')+'\n\n'+await readFile('licenses/LobeIcons-MIT.txt','utf8')+'\n\nShep original code and website:\n'+await readFile('LICENSE','utf8'));
console.log('Static site prepared in .local/site-dist. Only the listed site and media files are copied.');
